import React, { Component } from 'react';
import styles from "./code.module.scss";

export class NavCode extends Component<{}, {}>
{
    render()
    {
        return (
            <div className={styles["WordSection1"]} >
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Nav</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp; &nbsp;&nbsp;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>logoSrc</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>=</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>{'{'}</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>logo</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>{'}'}</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>links</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>=</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>{'{'}[</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;{'{'}</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>name</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>:</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>Home</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>",</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>to</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>:</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>",</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>key</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>:</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>home</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>{'}'},</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;{'{'}</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>name</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>:</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>Documentation</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>",</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>to</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>:</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>/documentation</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>",</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>key</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>:</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>doc</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>{'}'}</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>]</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>{'}'}</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>/&gt;</span></p>
            </div>
        );
    }
}