import React, { Component } from 'react';
import styles from "./code.module.scss";

export class EqualWidthCode extends Component<{}, {}>
{
    render()
    {
        return (
            <div className={styles["WordSection1"]} >
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Row</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Col</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Row</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
            </div>
        );
    }
}