import React, { Component } from 'react';
import styles from "./code.module.scss";

export class BasicCode extends Component<{}, {}>
{
    render()
    {
        return (
            <div className={styles["WordSection1"]} >
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>div</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>primary</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>primary</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>secondary</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>secondary</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>success</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>success</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; &lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>danger</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>danger</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>&nbsp;&nbsp;&nbsp; </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>warning</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>warning</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; &lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>info</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>info</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; &lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>light</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>light</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]} style={{ textAlign: 'left' }}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&nbsp;&nbsp;&nbsp; &lt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button </span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#0B8235' }}>type</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>="</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#008DFF' }}>dark</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>"&gt;</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#314659', background: 'white' }}>dark</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>Button</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
                <p className={styles["MsoNormal"]}><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&lt;/</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#F81D22' }}>div</span><span lang="EN-US" style={{ fontFamily: '"Lucida Console"', color: '#999999' }}>&gt;</span></p>
            </div>
        );
    }
}